### ISSUE TITLE
Encountering RuntimeError Related to Process Group Initialization on RTX 3090

### ISSUE THREAD

**Issue by larrywo** [Coobiw/MiniGPT4Qwen#1]
While attempting to train my model on an RTX 3090 GPU, I came across the following error: `RuntimeError: Default process group has not been initialized.` It seems like `init_process_group` has not been called.

I'd appreciate it if anyone could provide guidance on resolving this issue.

![image](https://github.com/Coobiw/MiniGPT4Qwen/assets/92247432/e3f911fe-bcb1-4edd-8491-dea405897b51)

**Comment by Coobiw** [comment]
I guess you didn't use DDP, which leads to this error because `dist.barrier()` without multi-process.
Just modify the `dist_barrier()` in runner_base.py to:
```
if is_dist_avail_and_initialized():
                dist.barrier()
```
Then it will work!
Now, this has been repaired. You can run `git pull` to get the latest code or refer to the commit: [https://github.com/Coobiw/MiniGPT4Qwen/commit/d13f9657614a6be7553c850b7f95b4c31832eeef](https://github.com/Coobiw/MiniGPT4Qwen/commit/d13f9657614a6be7553c850b7f95b4c31832eeef)
